# Generated by Django 4.1.7 on 2023-03-20 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb_app', '0003_movie_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='name',
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_name',
            field=models.CharField(default='sdfsdf', max_length=256),
            preserve_default=False,
        ),
    ]
