# Generated by Django 4.1.7 on 2023-03-20 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb_app', '0004_remove_movie_name_movie_movie_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='movie_name',
        ),
        migrations.AddField(
            model_name='movie',
            name='name',
            field=models.CharField(default='a', max_length=128),
            preserve_default=False,
        ),
    ]
